### ISSUE TITLE
Is it possible to define google maps or other base layers?

### ISSUE THREAD

**Issue by zmagyar77** [sourcepole/ol3-mobile-viewer#11]
I'd like to add some base layer to my map wms overlays! Is it possible to configure the topics to set some selectable base layers? 
Thanks!

**Comment by uhensler** [comment]
It is possible to define one background layer per topic e.g. `"bg_topic": "geo_admin_pk"`. This backgroundlayer has to be a WMS Layer. As far as I now does google maps not support WMS.

Have a look at https://github.com/sourcepole/ol3-mobile-viewer/blob/master/data/topics.json

**Comment by zmagyar77** [comment]
Thanks for your answer! I'll try it on this way. But it would be nice to add more base layer, like in OpenLayers, also Google Maps, and Bing layers.

Thanks again.
Zs.
