### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by tudorbarascu** [sourcepole/ol3-mobile-viewer#6]
Hi,

I want to add Romanian language support and push it here.

I'm thinking of adding to Translations.js something like I18n_language_code:
..............................
I18n_ro = {};
I18n_ro.title = "Mobile ...(OL3)";
I18n_ro.search = {
header: "Caută adrese",
................................

And then in the config.js:
I18n=I18n_ro;

Do you have any suggestion/comment?
Nice work!
Tudor

**Comment by urshensler** [comment]
Hi

My suggestion ist to copy src/translations.js to src/translations_ro.js and store the romanian terms in the new file.

Then you have just to change the reference in index.html to src/translations_ro.js.
```javascript
 <script src="src/translations_ro.js"></script>
```

Hope this helps.

**Comment by tudorbarascu** [comment]
Ty
